import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.scss'
import { usersService } from '@/services/user.service'
import { GetServerSideProps } from 'next'
import { AiDisclaimer } from '@cc/cc-common-ai-components'

const Home = ({ data }: { data: any[] }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>CC components try</h1>
        <AiDisclaimer open={true} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} layout="fixed" />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home

export const getServerSideProps: GetServerSideProps = async () => {
  const { data } = await usersService.getUser()

  return {
    props: {
      data,
    },
  }
}
